"""
generated by claude ai
20-20-20 Eye Rest Reminder + Transparent Clock Overlay
--------------------------------------------------------
1) A small transparent clock stays on top of your screen at all times,
   showing the current time in a clean font. Click and drag it anywhere.
2) Every REMINDER_INTERVAL_MINUTES, a popup reminds you to look at
   something 20 feet (~6 meters) away for 20 seconds, then auto-closes.

Requires only the Python standard library (tkinter) — nothing to install.
Note: true background transparency (-transparentcolor) is a Windows-only
tkinter feature, so this is designed for Windows.

Run it with:
    python eye_reminder_20_20_20.py

To stop it, just close the clock window (click the small "x" that
appears when you hover it), or press Ctrl+C in the console.
"""

import tkinter as tk

# ----- Settings you can change -----
REMINDER_INTERVAL_MINUTES = 60     # how often the eye-rest popup appears
LOOK_AWAY_SECONDS = 20               # how long the popup stays visible

CLOCK_FONT = ("Aero", 20)   # try "Segoe UI Light", "Bahnschrift Light", "Consolas"
CLOCK_COLOR = "#e8e8e8"                     # clock text color
CLOCK_SHADOW_COLOR = "#00adb5"              # subtle shadow/glow color
TRANSPARENT_KEY = "#010203"                 # magic color that becomes invisible (Windows only)
CLOCK_START_X = 40                          # initial position from left
CLOCK_START_Y = 20                          # initial position from top
# ------------------------------------


class ClockOverlay:
    def __init__(self, root):
        self.root = root
        self.root.overrideredirect(True)               # no borders/title bar
        self.root.attributes("-topmost", True)          # always on top
        self.root.configure(bg=TRANSPARENT_KEY)
        self.root.attributes("-transparentcolor", TRANSPARENT_KEY)
        self.root.geometry(f"+{CLOCK_START_X}+{CLOCK_START_Y}")

        # Shadow label (drawn slightly offset, behind) gives a soft glow look
        self.shadow_label = tk.Label(
            root, font=CLOCK_FONT, fg=CLOCK_SHADOW_COLOR, bg=TRANSPARENT_KEY
        )
        self.shadow_label.place(x=2, y=2)

        # Main clock label
        self.time_label = tk.Label(
            root, font=CLOCK_FONT, fg=CLOCK_COLOR, bg=TRANSPARENT_KEY
        )
        self.time_label.place(x=0, y=0)

        # Small close button, only visible on hover
        self.close_btn = tk.Label(
            root, text="✕", font=("Aero", 9), fg="#888888", bg=TRANSPARENT_KEY,
            cursor="hand2"
        )
        self.close_btn.place(relx=1.0, x=-2, y=-2, anchor="ne")
        self.close_btn.bind("<Button-1>", lambda e: root.destroy())

        # Make the clock draggable
        for widget in (self.time_label, self.shadow_label):
            widget.bind("<ButtonPress-1>", self.start_drag)
            widget.bind("<B1-Motion>", self.do_drag)

        self._drag_offset = (0, 0)
        self.update_clock()

    def start_drag(self, event):
        self._drag_offset = (event.x, event.y)

    def do_drag(self, event):
        x = self.root.winfo_pointerx() - self._drag_offset[0]
        y = self.root.winfo_pointery() - self._drag_offset[1]
        self.root.geometry(f"+{x}+{y}")

    def update_clock(self):
        current_time = self._now_string()
        self.time_label.config(text=current_time)
        self.shadow_label.config(text=current_time)
        self.root.after(1000, self.update_clock)

    @staticmethod
    def _now_string():
        import datetime
        return datetime.datetime.now().strftime("%H:%M:%S")


def show_reminder(root):
    """Creates and displays the 20-20-20 popup, then reschedules itself."""
    popup = tk.Toplevel(root)
    popup.attributes("-topmost", True)
    popup.overrideredirect(True)
    popup.attributes("-alpha", 0.95)

    popup_w, popup_h = 320, 120
    screen_w = popup.winfo_screenwidth()
    screen_h = popup.winfo_screenheight()
    x = screen_w - popup_w - 20
    y = screen_h - popup_h - 60
    popup.geometry(f"{popup_w}x{popup_h}+{x}+{y}")
    popup.configure(bg="#222831")

    tk.Label(
        popup, text="👀 وقت استراحت چشمه!", font=("Aero", 13, "bold"),
        bg="#222831", fg="#eeeeee"
    ).pack(pady=(15, 5))

    tk.Label(
        popup, text=f"{LOOK_AWAY_SECONDS} ثانیه به یه نقطه دور نگاه کن",
        font=("Aero", 11), bg="#222831", fg="#cccccc"
    ).pack()

    countdown_label = tk.Label(
        popup, text="", font=("Aero", 10), bg="#222831", fg="#00adb5"
    )
    countdown_label.pack(pady=(5, 0))

    def tick(remaining):
        if remaining <= 0:
            popup.destroy()
            return
        countdown_label.config(text=f"{remaining} ثانیه")
        popup.after(1000, tick, remaining - 1)

    tick(LOOK_AWAY_SECONDS)
    popup.bind("<Button-1>", lambda e: popup.destroy())

    # schedule the next reminder
    root.after(REMINDER_INTERVAL_MINUTES * 60 * 1000, show_reminder, root)


if __name__ == "__main__":
    root = tk.Tk()
    clock = ClockOverlay(root)

    # show one reminder immediately so you can see it works,
    # then it reschedules itself every REMINDER_INTERVAL_MINUTES
    root.after(2000, show_reminder, root)

    print("Clock overlay is running. Drag it with your mouse to move it.")
    print("Hover it and click the small (X) (top-right) to close everything.")
    root.mainloop()